// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDaadY83pjGf88bpBSk5bkO0JxEdSn4tA',
    appId: '1:532397582068:web:e2ddc88ce163ede77160a1',
    messagingSenderId: '532397582068',
    projectId: 'g13pals',
    authDomain: 'g13pals.firebaseapp.com',
    storageBucket: 'g13pals.firebasestorage.app',
    measurementId: 'G-FQ6MGE3ZYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUPjx65wwNddyi5CnXY3KWvzfZV29kSKs',
    appId: '1:532397582068:android:e79e0ea27fb7b3b17160a1',
    messagingSenderId: '532397582068',
    projectId: 'g13pals',
    storageBucket: 'g13pals.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATOKun8N4LBVO9E3M9uXsxWxmStbOQQ6k',
    appId: '1:532397582068:ios:4640e49bf2a233e57160a1',
    messagingSenderId: '532397582068',
    projectId: 'g13pals',
    storageBucket: 'g13pals.firebasestorage.app',
    iosBundleId: 'com.example.g13money',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATOKun8N4LBVO9E3M9uXsxWxmStbOQQ6k',
    appId: '1:532397582068:ios:4640e49bf2a233e57160a1',
    messagingSenderId: '532397582068',
    projectId: 'g13pals',
    storageBucket: 'g13pals.firebasestorage.app',
    iosBundleId: 'com.example.g13money',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDaadY83pjGf88bpBSk5bkO0JxEdSn4tA',
    appId: '1:532397582068:web:31376b08dff933027160a1',
    messagingSenderId: '532397582068',
    projectId: 'g13pals',
    authDomain: 'g13pals.firebaseapp.com',
    storageBucket: 'g13pals.firebasestorage.app',
    measurementId: 'G-D989C2T6ZB',
  );
}
